"""ratings carry title and year

Revision ID: 747b8ea3a582
Revises: 4190d441327d
Create Date: 2026-07-26 16:23:52.914849

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '747b8ea3a582'
down_revision: str | None = '4190d441327d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ratings",
        sa.Column("name", sa.String(length=500), nullable=False, server_default=""),
    )
    op.alter_column("ratings", "name", server_default=None)
    op.add_column('ratings', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'year')
    op.drop_column('ratings', 'name')
    # ### end Alembic commands ###
