"""add likes table

Revision ID: 8959d9ed298a
Revises: ab622457e86d
Create Date: 2026-07-26 06:10:58.550408

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8959d9ed298a'
down_revision: str | None = 'ab622457e86d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('letterboxd_uri', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_likes_upload', 'likes', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_likes_upload', table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
