"""initial schema

Revision ID: ab622457e86d
Revises: 
Create Date: 2026-07-26 05:58:58.919742

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ab622457e86d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The resolver's fuzzy fallback is a trigram similarity query against
    # films.normalized_title, so the extension has to exist before that index.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('media_type', sa.Enum('MOVIE', 'TV', name='media_type'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_index('ix_films_normalized_title', 'films', ['normalized_title'], unique=False)
    op.create_index('ix_films_year', 'films', ['year'], unique=False)
    op.create_table('people',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVING', 'FETCHING_CREDITS', 'MODELLING', 'COMPLETE', 'FAILED', name='upload_status'), nullable=False),
    sa.Column('film_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_token'), 'uploads', ['token'], unique=True)
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_upload', 'analysis_runs', ['upload_id'], unique=False)
    op.create_table('credits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('job', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.tmdb_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.tmdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('film_id', 'person_id', 'job', name='uq_credit')
    )
    op.create_index('ix_credits_film', 'credits', ['film_id'], unique=False)
    op.create_index('ix_credits_person', 'credits', ['person_id'], unique=False)
    op.create_table('diary_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('film_key', sa.String(length=500), nullable=False),
    sa.Column('watched_date', sa.Date(), nullable=True),
    sa.Column('is_rewatch', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diary_upload', 'diary_entries', ['upload_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('letterboxd_uri', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ratings_upload', 'ratings', ['upload_id'], unique=False)
    op.create_table('resolutions',
    sa.Column('letterboxd_uri', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('match_method', sa.Enum('EXACT', 'TRIGRAM', 'MANUAL', 'UNRESOLVED', name='match_method'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tmdb_id'], ['films.tmdb_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('letterboxd_uri')
    )
    op.create_table('crew_effects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.Float(), nullable=False),
    sa.Column('stderr', sa.Float(), nullable=True),
    sa.Column('n_films', sa.Integer(), nullable=False),
    sa.Column('inseparable_from_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inseparable_from_person_id'], ['people.tmdb_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.tmdb_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_effects_run_role', 'crew_effects', ['run_id', 'role'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('primary_reason_person_id', sa.Integer(), nullable=True),
    sa.Column('novelty_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.tmdb_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_reason_person_id'], ['people.tmdb_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recs_run', 'recommendations', ['run_id'], unique=False)
    # ### end Alembic commands ###

    # GIN + gin_trgm_ops is what makes similarity() cheap. The btree index above still
    # serves exact-title lookups; this one serves the fuzzy fallback.
    op.create_index(
        "ix_films_normalized_title_trgm",
        "films",
        ["normalized_title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized_title": "gin_trgm_ops"},
    )


def downgrade() -> None:
    op.drop_index("ix_films_normalized_title_trgm", table_name="films")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recs_run', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_effects_run_role', table_name='crew_effects')
    op.drop_table('crew_effects')
    op.drop_table('resolutions')
    op.drop_index('ix_ratings_upload', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('ix_diary_upload', table_name='diary_entries')
    op.drop_table('diary_entries')
    op.drop_index('ix_credits_person', table_name='credits')
    op.drop_index('ix_credits_film', table_name='credits')
    op.drop_table('credits')
    op.drop_index('ix_runs_upload', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_uploads_token'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_table('people')
    op.drop_index('ix_films_year', table_name='films')
    op.drop_index('ix_films_normalized_title', table_name='films')
    op.drop_table('films')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
